test log-parser plugin

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -70,107 +70,113 @@ pipeline {
                   pip install flake8 --user
                   flake8 cloudify_cli
                 '''
+                echo 'failed'
               }
             }
           }
         }
-        stage('build-rpm') {
-          steps {
-            container('rpmbuild') {
-              echo 'Copying repo to seperate workspace'
-              sh '''
-                cd && mkdir rpmbuild && cd rpmbuild
-                git clone https://github.com/cloudify-cosmo/cloudify-cli.git SOURCES && cd SOURCES
-              '''
-              echo 'Installing setup tools'
-              sh '''
-                yum install python-setuptools -y
-                chmod a+wx /opt
-              '''
-              sh script:'''
-                cd ~/rpmbuild/SOURCES
-                yum-builddep -y packaging/cloudify-cli.spec
-                rpmbuild \
-                  -D "CLOUDIFY_VERSION $(python setup.py --version | cut -d- -f1)" \
-                  -D "CLOUDIFY_PACKAGE_RELEASE 1" \
-                  -bb packaging/cloudify-cli.spec
-              ''', label: "building dependencies and rpm"
-              sh script:("mkdir -p ${env.WORKSPACE}/rpm_artifacts && cp -rf /root/rpmbuild/RPMS/x86_64/. ${env.WORKSPACE}/rpm_artifacts"), label: "Copy RPM to rpm_artifacts folder"
-            }
-          }
-          post {
-            success {
-              archiveArtifacts '**/rpm_artifacts/*.rpm'
-            }
-          }
-        }
-        stage('build-deb') {
-          steps {
-            sh script: "mkdir -p ${env.WORKSPACE}/project && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/project", label: "copying repo to seperate workspace"
-            container('debbuild') {
-              sh script: 'mkdir /tmp/result', label: "create result folder"
-              echo 'install python setup tools'
-              sh'''
-                set -ex
-                apt-get update
-                apt-get install python3 python3-setuptools python3-distutils -y
-              '''
-              sh script: "/bin/bash ${env.WORKSPACE}/project/packaging/debian/build.sh", label: "build the deb package"
-              sh script: """
-                set -ex
-                rm -rf /opt/cfy
-                dpkg -i /tmp/result/*.deb
-                cfy --version
-              """, label: "sanity-test the deb package"
-              sh script:("mkdir -p ${env.WORKSPACE}/deb_artifacts && cp -rf /tmp/result/*.deb ${env.WORKSPACE}/deb_artifacts"), label: "Copy RPM to deb_artifacts folder"
-            }
-          }
-          post {
-            success {
-              archiveArtifacts '**/deb_artifacts/*.deb'
-            }
-          }
-        }
+        // stage('build-rpm') {
+        //   steps {
+        //     container('rpmbuild') {
+        //       echo 'Copying repo to seperate workspace'
+        //       sh '''
+        //         cd && mkdir rpmbuild && cd rpmbuild
+        //         git clone https://github.com/cloudify-cosmo/cloudify-cli.git SOURCES && cd SOURCES
+        //       '''
+        //       echo 'Installing setup tools'
+        //       sh '''
+        //         yum install python-setuptools -y
+        //         chmod a+wx /opt
+        //       '''
+        //       sh script:'''
+        //         cd ~/rpmbuild/SOURCES
+        //         yum-builddep -y packaging/cloudify-cli.spec
+        //         rpmbuild \
+        //           -D "CLOUDIFY_VERSION $(python setup.py --version | cut -d- -f1)" \
+        //           -D "CLOUDIFY_PACKAGE_RELEASE 1" \
+        //           -bb packaging/cloudify-cli.spec
+        //       ''', label: "building dependencies and rpm"
+        //       sh script:("mkdir -p ${env.WORKSPACE}/rpm_artifacts && cp -rf /root/rpmbuild/RPMS/x86_64/. ${env.WORKSPACE}/rpm_artifacts"), label: "Copy RPM to rpm_artifacts folder"
+        //     }
+        //   }
+        //   post {
+        //     success {
+        //       archiveArtifacts '**/rpm_artifacts/*.rpm'
+        //     }
+        //   }
+        // }
+        // stage('build-deb') {
+        //   steps {
+        //     sh script: "mkdir -p ${env.WORKSPACE}/project && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/project", label: "copying repo to seperate workspace"
+        //     container('debbuild') {
+        //       sh script: 'mkdir /tmp/result', label: "create result folder"
+        //       echo 'install python setup tools'
+        //       sh'''
+        //         set -ex
+        //         apt-get update
+        //         apt-get install python3 python3-setuptools python3-distutils -y
+        //       '''
+        //       sh script: "/bin/bash ${env.WORKSPACE}/project/packaging/debian/build.sh", label: "build the deb package"
+        //       sh script: """
+        //         set -ex
+        //         rm -rf /opt/cfy
+        //         dpkg -i /tmp/result/*.deb
+        //         cfy --version
+        //       """, label: "sanity-test the deb package"
+        //       sh script:("mkdir -p ${env.WORKSPACE}/deb_artifacts && cp -rf /tmp/result/*.deb ${env.WORKSPACE}/deb_artifacts"), label: "Copy RPM to deb_artifacts folder"
+        //     }
+        //   }
+        //   post {
+        //     success {
+        //       archiveArtifacts '**/deb_artifacts/*.deb'
+        //     }
+        //   }
+        // }
       }
     }
-    stage('pytests') {
-      parallel {
-        stage('test_py27') {
-          steps {
-            sh script: "mkdir -p ${env.WORKSPACE}/test_py27 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/test_py27", label: "copying repo to seperate workspace"
-            container('py27') {
-              dir("${env.WORKSPACE}/test_py27") {
-                echo 'create virtual env'
-                sh 'virtualenv ~/venv'
-                install_test_dependencies()
-                pytest()
-              }
-            }
-          }
-          post {
-            always {
-              junit '**/test-results/*.xml'
-            }
-          }
-        }
-        stage('test_py36') {
-          steps {
-            sh script: "mkdir -p ${env.WORKSPACE}/test_py36 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/test_py36", label: "copying repo to seperate workspace"
-            container('py36') {
-              dir("${env.WORKSPACE}/test_py36") {
-                echo 'create virtual env'
-                sh 'virtualenv ~/venv'
-                install_test_dependencies()
-                pytest()
-              }
-            }
-          }
-          post {
-            always {
-              junit '**/test-results/*.xml'
-            }
-          }
-        }
+    // stage('pytests') {
+    //   parallel {
+    //     stage('test_py27') {
+    //       steps {
+    //         sh script: "mkdir -p ${env.WORKSPACE}/test_py27 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/test_py27", label: "copying repo to seperate workspace"
+    //         container('py27') {
+    //           dir("${env.WORKSPACE}/test_py27") {
+    //             echo 'create virtual env'
+    //             sh 'virtualenv ~/venv'
+    //             install_test_dependencies()
+    //             pytest()
+    //           }
+    //         }
+    //       }
+    //       post {
+    //         always {
+    //           junit '**/test-results/*.xml'
+    //         }
+    //       }
+    //     }
+    //     stage('test_py36') {
+    //       steps {
+    //         sh script: "mkdir -p ${env.WORKSPACE}/test_py36 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/test_py36", label: "copying repo to seperate workspace"
+    //         container('py36') {
+    //           dir("${env.WORKSPACE}/test_py36") {
+    //             echo 'create virtual env'
+    //             sh 'virtualenv ~/venv'
+    //             install_test_dependencies()
+    //             pytest()
+    //           }
+    //         }
+    //       }
+    //       post {
+    //         always {
+    //           junit '**/test-results/*.xml'
+    //         }
+    //       }
+    //     }
+    //   }
+    // }
+    stage('check failed'){
+      steps{
+        step([$class: 'LogParserPublisher', failBuildOnError: true, parsingRulesPath: '/tmp/system-tests-rules', useProjectRule: false])
       }
     }
   }
